name: Laravel Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  laravel-tests:
    name: PHP ${{ matrix.php-version }} - Laravel Tests
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-version: ["8.2"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          coverage: none

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v3
        with:
          composer-options: "--prefer-dist --no-interaction"

      - name: Prepare Laravel Application
        run: |
          cp .env.testing .env
          php artisan key:generate

      # Removed the failing check-style step

      - name: Run Unit and Feature Tests
        run: |
          echo "CACHE_DRIVER=array" >> .env
          php artisan config:clear
          php artisan migrate:fresh --env=testing --seed --force
          php artisan test
